export const routes = {
  home: '/',
  platformProviders: '/platform-administration/platform-providers',
  platformConfiguration: '/platform-administration/configuration',
  platformIdentityAccess: '/platform-administration/identity-access',
  platformAuditRetention: '/platform-administration/audit-retention',
  providersConnectors: '/providers-connectors/providers',
  providerCredentials: '/providers-connectors/credentials',
  providerDiscoverySettings: '/providers-connectors/discovery-settings',
  recoveryApplications: '/recovery-plans/recovery-applications',
  recoveryGroups: '/recovery-plans/recovery-groups',
  snapshotPolicies: '/recovery-plans/snapshot-policies',
  recoveryAppPolicies: '/recovery-plans/recovery-app-policies',
  policySets: '/recovery-plans/policy-sets',
  recoveryRuns: '/recovery-plans/recovery-runs',
  resources: '/discovery-inventory/resources',
  infrastructure: '/discovery-inventory/infrastructure',
  discoveryJobs: '/discovery-inventory/discovery-jobs',
  storageOrchestration: '/storage-orchestration',
  recoveryPlans: '/recovery-plans',
} as const
